// Agent action endpoints
module.exports = function registerAgentRoutes(app, deps){
  const { createAgentAuth, agentActionRunner, aiAgent, AGENT_TOKEN, appendLog, getConsoleMirrorState, setConsoleMirror } = deps;
  const requireAgentAuth = createAgentAuth({ agentActionRunner, token: AGENT_TOKEN });
  app.get('/api/agent/actions', requireAgentAuth, (req,res)=>{ try { res.json({ success:true, actions: agentActionRunner.listActions() }); } catch(e){ res.status(500).json({ success:false, error:e.message }); } });
  app.post('/api/agent/run', requireAgentAuth, (req,res)=>{ try { const { action, config } = req.body || {}; if(!action) return res.status(400).json({ success:false, error:'action required' }); const result = agentActionRunner.execute(action, { config, aiAgent }); res.json({ success: !!result.started || result.success, result }); } catch(e){ res.status(500).json({ success:false, error:e.message }); } });
  app.post('/api/agent/kill', requireAgentAuth, (req,res)=>{ try { const { processId } = req.body || {}; if(!processId) return res.status(400).json({ success:false, error:'processId required'}); res.json(agentActionRunner.kill(processId)); } catch(e){ res.status(500).json({ success:false, error:e.message }); } });
  app.post('/api/agent/provider', requireAgentAuth, (req,res)=>{ try { const { provider } = req.body || {}; if(!provider) return res.status(400).json({ success:false, error:'provider required'}); if(!aiAgent) return res.status(503).json({ success:false, error:'ai agent disabled'}); const ok = aiAgent.setProvider(provider); res.json({ success: ok, provider, active: aiAgent.config.defaultProvider }); } catch(e){ res.status(500).json({ success:false, error:e.message }); } });
  app.get('/api/agent/health', requireAgentAuth, (req,res)=>{ try { res.json({ success:true, agent: aiAgent ? aiAgent.getHealth(): null, runner: !!agentActionRunner }); } catch(e){ res.status(500).json({ success:false, error:e.message }); } });
  app.get('/api/logging/console', requireAgentAuth, (req,res)=>{ try { res.json({ success:true, state:getConsoleMirrorState() }); } catch(e){ res.status(500).json({ success:false, error:e.message }); } });
  app.post('/api/logging/console', requireAgentAuth, (req,res)=>{ try { const { enable, channels } = req.body || {}; const state = setConsoleMirror(!!enable, Array.isArray(channels)? channels : (channels===null ? null : undefined)); appendLog('node', `console-mirror ${state.enabled? 'enabled':'disabled'} channels=${state.channels? state.channels.join(','):'*'}`); res.json({ success:true, state }); } catch(e){ res.status(500).json({ success:false, error:e.message }); } });
};
