// Serial & Improv related routes
// Encapsulates endpoints originally defined inline in server.js
module.exports = function registerSerialRoutes(app, deps){
  const { serialManager, appendLog, currentConfigRef, DEFAULT_SERIAL_COMMANDS, buildImprovRpc, buildWifiSettingsPayload, CMD_GET_WIFI_NETWORKS, TYPE_RPC_RESPONSE, decodeRpcPayload, CMD_WIFI_SETTINGS, parseImprovFrames, rateLimit } = deps;

  // List ports
  app.get('/api/serial/list', async (req,res)=>{ if(!serialManager) return res.json({ success:false, error:'serial manager not available' }); try { const ports = await serialManager.listPorts(); res.json({ success:true, ports }); } catch(e){ res.json({ success:false, error:e.message }); } });
  // Status
  app.get('/api/serial/status', (req,res)=>{ if(!serialManager) return res.json({ success:true, status:{ available:false }, note:'serial manager disabled' }); try { res.json({ success:true, status: serialManager.getStatus() }); } catch(e){ res.status(500).json({ success:false, error:e.message }); } });
  // Open
  app.post('/api/serial/open', async (req,res)=>{
    if(!serialManager || !serialManager.isAvailable()) return res.status(501).json({ success:false, error:'serialport not available on server' });
    const { path: portPath, baudRate=115200, openTimeout } = req.body || {}; if(!portPath) return res.status(400).json({ success:false, error:'path required' });
    try { let orig = serialManager._openTimeoutMs; if(openTimeout && Number.isFinite(openTimeout)) serialManager._openTimeoutMs = parseInt(openTimeout,10); appendLog('serial', `open_request path=${portPath} baud=${baudRate} timeout=${serialManager._openTimeoutMs}`); const started=Date.now(); try { const result = await serialManager.open(portPath, baudRate); const elapsed=Date.now()-started; appendLog('serial', `open_success path=${portPath} elapsedMs=${elapsed}`); res.json({ success:true, elapsedMs: elapsed, ...result }); } finally { serialManager._openTimeoutMs = orig; } } catch(e){ appendLog('serial', `open_fail path=${portPath} err=${e.message||e}`); res.status(500).json({ success:false, error:e.message }); }
  });
  // Close
  app.post('/api/serial/close', async (req,res)=>{ if(!serialManager) return res.json({ success:true, alreadyClosed:true }); const { path: portPath } = req.body || {}; const st = serialManager.getStatus(); if(portPath && st.path && portPath !== st.path) return res.json({ success:false, error:'different port currently open', status: st }); try { const result = await serialManager.close(); res.json({ success: !!result.success, ...result }); } catch(e){ res.status(500).json({ success:false, error:e.message }); } });
  // Write
  app.post('/api/serial/write', async (req,res)=>{ if(!serialManager) return res.status(501).json({ success:false, error:'serial manager not available' }); const { path: portPath, data } = req.body||{}; if(!portPath || data===undefined) return res.status(400).json({ success:false, error:'path and data required' }); const st = serialManager.getStatus(); if(!st.open || st.path !== portPath) return res.status(400).json({ success:false, error:'port not open' }); try { const autoNL = req.query && req.query.autoNL === '1'; let payload = data; if(autoNL && typeof payload==='string' && !payload.endsWith('\n')) payload+='\n'; await serialManager.write(payload); res.json({ success:true }); } catch(e){ res.status(500).json({ success:false, error:e.message }); } });
  // Reopen
  app.post('/api/serial/reopen', async (req,res)=>{ try { if(!serialManager || !serialManager.isAvailable()) return res.status(501).json({ success:false, error:'serialport not available on server' }); const { path: portPath, baudRate } = req.body || {}; const targetPort = portPath || currentConfigRef.value.comPort; const targetBaud = parseInt(baudRate,10) || currentConfigRef.value.baudRate || 115200; const st = serialManager.getStatus(); if(st.open && (st.path !== targetPort || st.baudRate !== targetBaud)) await serialManager.close(); const result = await serialManager.open(targetPort, targetBaud); currentConfigRef.value.comPort = targetPort; currentConfigRef.value.baudRate = targetBaud; res.json({ success:true, result, status: serialManager.getStatus() }); } catch(e){ res.status(400).json({ success:false, error:e.message }); } });
  // Diagnose
  app.get('/api/serial/diagnose', async (req,res)=>{ try { if(!serialManager || !serialManager.isAvailable()) return res.status(501).json({ success:false, error:'serialport not available on server' }); const status = serialManager.getStatus(); let poked=false; if(status.open){ try { await serialManager.write('\n'); poked=true; } catch(_){} } res.json({ success:true, status, poked }); } catch(e){ res.status(500).json({ success:false, error:e.message }); } });
  // Serial commands list
  app.get('/api/serial/commands', (req,res)=>{ try { const q = (req.query.q||'').toString().trim().toLowerCase(); let cmds = DEFAULT_SERIAL_COMMANDS.slice(); if(q) cmds = cmds.filter(c=>c.toLowerCase().startsWith(q)); res.json({ success:true, commands: cmds }); } catch(e){ res.status(500).json({ success:false, error:e.message }); } });
  // WiFi scan via Improv
  app.post('/api/serial/wifi/scan', async (req,res)=>{ if(!serialManager || !serialManager.isAvailable()) return res.status(501).json({ success:false, error:'serialport not available on server' }); const { path: portPath, baudRate=115200, timeoutMs=8000 } = req.body||{}; if(!portPath) return res.status(400).json({ success:false, error:'path required' }); if(currentConfigRef.value.manualComOnly && currentConfigRef.value.allowedComPort){ const allowed = String(currentConfigRef.value.allowedComPort).toUpperCase(); if(String(portPath).toUpperCase() !== allowed) return res.status(403).json({ success:false, error:`Manual COM mode active. Only ${allowed} is allowed.` }); }
    let tempPort=null; try { const status = serialManager.getStatus(); let port; if(status.open && status.path===portPath){ port = serialManager._port; } else { const spLib = require('serialport'); const SP = spLib.SerialPort || spLib; port = new SP({ path: portPath, baudRate: parseInt(baudRate,10) }); try { port.on('error', e=>appendLog('serial', `wifi_scan error path=${portPath} err=${e.message||e}`)); } catch(_){} tempPort=port; }
    const frame = buildImprovRpc(CMD_GET_WIFI_NETWORKS); await new Promise((resolve,reject)=>{ try { port.write(frame, err=> err?reject(err):resolve()); } catch(e){ reject(e); } }); const networks=[]; let buf = Buffer.alloc(0); let done=false; const onData = data => { buf = Buffer.concat([buf, Buffer.isBuffer(data)? data : Buffer.from(data)]); buf = parseImprovFrames(buf, fr=>{ if(fr.typ!==TYPE_RPC_RESPONSE) return; const { cmd, items } = decodeRpcPayload(fr.payload); if(cmd===CMD_GET_WIFI_NETWORKS){ if(!items || items.length===0){ done=true; return; } const ssid = items[0]||''; const rssi = items[1]? Number(items[1]) : 0; const auth = items[2]||''; if(ssid) networks.push({ ssid, rssi, auth }); } }); };
    port.on('data', onData); const started = Date.now(); while(!done && (Date.now()-started) < timeoutMs){ await new Promise(r=>setTimeout(r,100)); } try { port.removeListener('data', onData); } catch(_){} if(tempPort){ try { await new Promise(r=> tempPort.close(()=>r())); } catch(_){} } return res.json({ success:true, networks }); } catch(err){ if(tempPort){ try { await new Promise(r=> tempPort.close(()=>r())); } catch(_){} } return res.status(500).json({ success:false, error: err.message || String(err) }); }
  });
  // WiFi connect via Improv
  app.post('/api/serial/wifi/connect', async (req,res)=>{ if(!serialManager || !serialManager.isAvailable()) return res.status(501).json({ success:false, error:'serialport not available on server' }); const { path: portPath, ssid, password='', baudRate=115200 } = req.body||{}; if(!portPath || !ssid) return res.status(400).json({ success:false, error:'path and ssid required' }); if(currentConfigRef.value.manualComOnly && currentConfigRef.value.allowedComPort){ const allowed = String(currentConfigRef.value.allowedComPort).toUpperCase(); if(String(portPath).toUpperCase() !== allowed) return res.status(403).json({ success:false, error:`Manual COM mode active. Only ${allowed} is allowed.` }); }
    let tempPort=null; try { const status = serialManager.getStatus(); let port; if(status.open && status.path===portPath){ port = serialManager._port; } else { const spLib = require('serialport'); const SP = spLib.SerialPort || spLib; port = new SP({ path: portPath, baudRate: parseInt(baudRate,10) }); try { port.on('error', e=>appendLog('serial', `wifi_connect error path=${portPath} err=${e.message||e}`)); } catch(_){} tempPort=port; }
    const payload = buildWifiSettingsPayload(ssid, password); const frame = buildImprovRpc(CMD_WIFI_SETTINGS, payload); await new Promise((resolve,reject)=>{ try { port.write(frame, err=> err?reject(err):resolve()); } catch(e){ reject(e); } }); let received=false; let buf = Buffer.alloc(0); const onData = data => { buf = Buffer.concat([buf, Buffer.isBuffer(data)? data : Buffer.from(data)]); buf = parseImprovFrames(buf, fr=>{ if(fr.typ!==TYPE_RPC_RESPONSE) return; const { cmd } = decodeRpcPayload(fr.payload); if(cmd===CMD_WIFI_SETTINGS) received=true; }); }; port.on('data', onData); const started=Date.now(); while(!received && (Date.now()-started)<3000){ await new Promise(r=>setTimeout(r,100)); } try { port.removeListener('data', onData); } catch(_){} if(tempPort){ try { await new Promise(r=> tempPort.close(()=>r())); } catch(_){} } return res.json({ success:true, acknowledged: received }); } catch(err){ if(tempPort){ try { await new Promise(r=> tempPort.close(()=>r())); } catch(_){} } return res.status(500).json({ success:false, error: err.message || String(err) }); }
  });
  // COM health check
  app.post('/api/com/check', async (req,res)=>{ if(!serialManager || !serialManager.isAvailable()) return res.status(501).json({ success:false, error:'serialport not available on server' }); const { path: portPath, baudRate=115200, testCmd='\n', timeout=1000 } = req.body||{}; if(!portPath) return res.status(400).json({ success:false, error:'path required' }); if(currentConfigRef.value.manualComOnly && currentConfigRef.value.allowedComPort){ const allowed = String(currentConfigRef.value.allowedComPort).toUpperCase(); if(String(portPath).toUpperCase() !== allowed) return res.status(403).json({ success:false, error:`Manual COM mode active. Only ${allowed} is allowed.` }); }
    let tempOpened=false; let port; let portErrored=null; try { const status = serialManager.getStatus(); if(status.open && status.path===portPath){ port = serialManager._port; } else { const spLib = require('serialport'); const SP = spLib.SerialPort || spLib; port = new SP({ path: portPath, baudRate: parseInt(baudRate,10) }); try { port.on('error', e=>{ portErrored=e; appendLog('serial', `com_check error-event path=${portPath} err=${e.message||e}`); }); } catch(_){} tempOpened=true; } let captured=''; const onData = data => { captured += data.toString(); }; port.on('data', onData); if(portErrored) throw portErrored; await new Promise((resolve,reject)=>{ try { port.write(testCmd, err=> err?reject(err):resolve()); } catch(err){ reject(err); } }); const toMs = parseInt(timeout,10); let waited=0; while(waited < toMs && !portErrored){ await new Promise(r=>setTimeout(r,50)); waited+=50; } port.removeListener('data', onData); if(tempOpened){ try { port.close(()=>{}); } catch(e){} } if(portErrored){ appendLog('serial', `com_check failed path=${portPath} err=${portErrored.message||portErrored}`); return res.status(500).json({ success:false, error: portErrored.message || String(portErrored) }); } appendLog('serial', `com_check path=${portPath} resp=${captured.replace(/\r?\n/g,'\\n')}`); return res.json({ success:true, response: captured }); } catch(err){ if(tempOpened && port && port.close){ try { port.close(()=>{}); } catch(e){} } appendLog('serial', `com_check error path=${portPath} err=${err.message||err}`); return res.status(500).json({ success:false, error: err.message || String(err) }); }
  });
};
